#!/usr/bin/env bash

export GOROOT="$HOME/go1.5"
export GOPATH="$HOME/go:$HOME/go1.5"
if [[ "$PATH" != "$GOBIN"* ]]; then
  export PATH="$GOBIN:$PATH"
fi

alias gogh='cd "$HOME/go/src/github.com"'
alias gome='cd "$HOME/go/src/github.com/lenguti"'
