export PATH="$PATH:$HOME/Projects/scripts"
export PATH=$PATH:/usr/local/sbin
export GOPATH="${HOME}/go"

source ~/.prompt

alias gst="git status"
alias gc="git commit -m"
alias gs="git stash"
alias gsp="git stash pop"
alias gco="git checkout"
alias gb="git branch"
alias ga="git add"
alias gpl="git pull --rebase"
alias gd="git diff"
alias grh="git reset HEAD"
alias gl="git log --oneline --decorate"
alias cdp="cd ~/Projects/"
alias md="cd ~/Projects/mdlive"
alias st="cd ~/Projects/stern"
alias fr="cd ~/Projects/Fore"
alias pp="cd ~/Projects/patient-portal"
alias ls="ls -G -al"
alias t="tmux"
alias log="tail -f log/development.log"
alias notes="cd ~/notes"
alias nx="sudo nginx"
alias nxs="sudo nginx -s stop"
alias b="bundle"
alias vi="vim"
alias mysql="mysql -uroot"
alias rc="rails c"
alias dm="eval "'"$(docker-machine env mdlive)"'""
alias gome="cd ~/go"
alias gop="cd ~/go/src/bitbucket.org/mlcloud/"
